[package]
name = "emulator"
version = "0.1.0"
authors = ["Naoto Ikeno <ikenox@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
edg-core = {path = "../edg-core"}
yew = "0.17.4"
wasm-bindgen = "0.2"
itertools = "0.10.0"
