[package]
name = "emulator"
version = "0.1.0"
authors = ["Naoto Ikeno <ikenox@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
keymap = {path = "../keymap"}
yew = "0.17.4"
wasm-bindgen = "0.2"