[package]
name = "edg-core"
version = "0.1.0"
authors = ["Naoto Ikeno <ikenox@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = { version = "0.5.2", disable-default-features = true}
hashbrown = "0.9.1"
